export const midMajors = [
  1, 46, 5, 6, 9, 10, 45, 12, 13, 14, 16, 18, 19, 20, 22, 24, 25, 26, 49, 27,
  29, 30,
];

export const majorConfs = [2, 62, 3, 8, 7, 4, 11, 44, 23, 21];

export const conferences = [
  {
    display: 'A 10',
    id: 3,
    value: 'a-10',
  },
  {
    display: 'A-Sun',
    id: 46,
    value: 'a-sun',
  },
  {
    display: 'ACC',
    id: 2,
    value: 'acc',
  },
  {
    display: 'Am. East',
    id: 1,
    value: 'am-east',
  },
  {
    display: 'American',
    id: 62,
    value: 'american',
  },
  {
    display: 'Big 12',
    id: 8,
    value: 'big-12',
  },
  {
    display: 'Big East',
    id: 4,
    value: 'big-east',
  },
  {
    display: 'Big Sky',
    id: 5,
    value: 'big-sky',
  },
  {
    display: 'Big South',
    id: 6,
    value: 'big-south',
  },
  {
    display: 'Big Ten',
    id: 7,
    value: 'big-ten',
  },
  {
    display: 'Big West',
    id: 9,
    value: 'big-west',
  },
  {
    display: 'C-USA',
    id: 11,
    value: 'c-usa',
  },
  {
    display: 'CAA',
    id: 10,
    value: 'caa',
  },
  {
    display: 'Horizon',
    id: 45,
    value: 'horizon',
  },
  {
    display: 'Ivy',
    id: 12,
    value: 'ivy',
  },
  {
    display: 'MAAC',
    id: 13,
    value: 'maac',
  },
  {
    display: 'MAC',
    id: 14,
    value: 'mac',
  },
  {
    display: 'MEAC',
    id: 16,
    value: 'meac',
  },
  {
    display: 'MVC',
    id: 18,
    value: 'mvc',
  },
  {
    display: 'MW',
    id: 44,
    value: 'mw',
  },
  {
    display: 'NEC',
    id: 19,
    value: 'nec',
  },
  {
    display: 'OVC',
    id: 20,
    value: 'ovc',
  },
  {
    display: 'Pac-12',
    id: 21,
    value: 'pac-12',
  },
  {
    display: 'Patriot',
    id: 22,
    value: 'patriot',
  },
  {
    display: 'SEC',
    id: 23,
    value: 'sec',
  },
  {
    display: 'SWAC',
    id: 26,
    value: 'swac',
  },
  {
    display: 'Southern',
    id: 24,
    value: 'southern',
  },
  {
    display: 'Southland',
    id: 25,
    value: 'southland',
  },
  {
    display: 'Summit',
    id: 49,
    value: 'summit',
  },
  {
    display: 'Sun Belt',
    id: 27,
    value: 'sun-belt',
  },
  {
    display: 'WAC',
    id: 30,
    value: 'wac',
  },
  {
    display: 'WCC',
    id: 29,
    value: 'wcc',
  },
];

const teams = [
  {
    id: '2000',
    name: 'Abilene Christian',
    statName: 'Abilene Christian',
    kpName: 'Abilene Christian',
  },
  {
    id: '2005',
    name: 'Air Force',
    statName: 'Air Force',
    kpName: 'Air Force',
  },
  {
    id: '2006',
    name: 'Akron',
    statName: 'Akron',
    kpName: 'Akron',
  },
  {
    id: '2010',
    name: 'Alabama A&M',
    statName: 'Alabama A&M',
    kpName: 'Alabama A&M',
  },
  {
    id: '333',
    name: 'Alabama',
    statName: 'Alabama',
    kpName: 'Alabama',
  },
  {
    id: '2011',
    name: 'Alabama State',
    statName: 'Alabama State',
    kpName: 'Alabama St.',
  },
  {
    id: '399',
    name: 'Albany',
    statName: 'Albany (NY)',
    kpName: 'Albany',
  },
  {
    id: '2016',
    name: 'Alcorn State',
    statName: 'Alcorn State',
    kpName: 'Alcorn St.',
  },
  {
    id: '44',
    name: 'American',
    statName: 'American',
    kpName: 'American',
  },
  {
    id: '2026',
    name: 'Appalachian State',
    statName: 'Appalachian State',
    kpName: 'Appalachian St.',
  },
  {
    id: '9',
    name: 'Arizona State',
    statName: 'Arizona State',
    kpName: 'Arizona St.',
  },
  {
    id: '12',
    name: 'Arizona',
    statName: 'Arizona',
    kpName: 'Arizona',
  },
  {
    id: '8',
    name: 'Arkansas',
    statName: 'Arkansas',
    kpName: 'Arkansas',
  },
  {
    id: '2032',
    name: 'Arkansas State',
    statName: 'Arkansas State',
    kpName: 'Arkansas St.',
  },
  {
    id: '2029',
    name: 'Arkansas-Pine Bluff',
    statName: 'Arkansas-Pine Bluff',
    kpName: 'Arkansas Pine Bluff',
  },
  {
    id: '349',
    name: 'Army',
    statName: 'Army',
    kpName: 'Army',
  },
  {
    id: '2',
    name: 'Auburn',
    statName: 'Auburn',
    kpName: 'Auburn',
  },
  {
    id: '2046',
    name: 'Austin Peay',
    statName: 'Austin Peay',
    kpName: 'Austin Peay',
  },
  {
    id: '252',
    name: 'BYU',
    statName: 'Brigham Young',
    kpName: 'BYU',
  },
  {
    id: '2050',
    name: 'Ball State',
    statName: 'Ball State',
    kpName: 'Ball St.',
  },
  {
    id: '239',
    name: 'Baylor',
    statName: 'Baylor',
    kpName: 'Baylor',
  },
  {
    id: '2057',
    name: 'Belmont',
    statName: 'Belmont',
    kpName: 'Belmont',
  },
  {
    id: '2065',
    name: 'Bethune-Cookman',
    statName: 'Bethune-Cookman',
    kpName: 'Bethune Cookman',
  },
  {
    id: '2066',
    name: 'Binghamton',
    statName: 'Binghamton',
    kpName: 'Binghamton',
  },
  {
    id: '68',
    name: 'Boise State',
    statName: 'Boise State',
    kpName: 'Boise St.',
  },
  {
    id: '103',
    name: 'Boston College',
    statName: 'Boston College',
    kpName: 'Boston College',
  },
  {
    id: '104',
    name: 'Boston University',
    statName: 'Boston University',
    kpName: 'Boston University',
  },
  {
    id: '189',
    name: 'Bowling Green',
    statName: 'Bowling Green State',
    kpName: 'Bowling Green',
  },
  {
    id: '71',
    name: 'Bradley',
    statName: 'Bradley',
    kpName: 'Bradley',
  },
  {
    id: '225',
    name: 'Brown',
    statName: 'Brown',
    kpName: 'Brown',
  },
  {
    id: '2803',
    name: 'Bryant',
    statName: 'Bryant',
    kpName: 'Bryant',
  },
  {
    id: '2083',
    name: 'Bucknell',
    statName: 'Bucknell',
    kpName: 'Bucknell',
  },
  {
    id: '2084',
    name: 'Buffalo',
    statName: 'Buffalo',
    kpName: 'Buffalo',
  },
  {
    id: '2086',
    name: 'Butler',
    statName: 'Butler',
    kpName: 'Butler',
  },
  {
    id: '2934',
    name: 'CSU Bakersfield',
    statName: 'Cal State Bakersfield',
    kpName: 'Cal St. Bakersfield',
  },
  {
    id: '2239',
    name: 'CSU Fullerton',
    statName: 'Cal State Fullerton',
    kpName: 'Cal St. Fullerton',
  },
  {
    id: '2463',
    name: 'CSU Northridge',
    statName: 'Cal State Northridge',
    kpName: 'Cal St. Northridge',
  },
  {
    id: '13',
    name: 'Cal Poly',
    statName: 'Cal Poly',
    kpName: 'Cal Poly',
  },
  {
    id: '2856',
    name: 'California Baptist',
    statName: 'California Baptist',
    kpName: 'Cal Baptist',
  },
  {
    id: '25',
    name: 'California',
    statName: 'University of California',
    kpName: 'California',
  },
  {
    id: '2097',
    name: 'Campbell',
    statName: 'Campbell',
    kpName: 'Campbell',
  },
  {
    id: '2099',
    name: 'Canisius',
    statName: 'Canisius',
    kpName: 'Canisius',
  },
  {
    id: '2110',
    name: 'Central Arkansas',
    statName: 'Central Arkansas',
    kpName: 'Central Arkansas',
  },
  {
    id: '2115',
    name: 'Central Connecticut',
    statName: 'Central Connecticut State',
    kpName: 'Central Connecticut',
  },
  {
    id: '2117',
    name: 'Central Michigan',
    statName: 'Central Michigan',
    kpName: 'Central Michigan',
  },
  {
    id: '232',
    name: 'Charleston',
    statName: 'College of Charleston',
    kpName: 'Charleston',
  },
  {
    id: '2127',
    name: 'Charleston Southern',
    statName: 'Charleston Southern',
    kpName: 'Charleston Southern',
  },
  {
    id: '2429',
    name: 'Charlotte',
    statName: 'Charlotte',
    kpName: 'Charlotte',
  },
  {
    id: '236',
    name: 'Chattanooga',
    statName: 'Chattanooga',
    kpName: 'Chattanooga',
  },
  {
    id: '2130',
    name: 'Chicago State',
    statName: 'Chicago State',
    kpName: 'Chicago St.',
  },
  {
    id: '2132',
    name: 'Cincinnati',
    statName: 'Cincinnati',
    kpName: 'Cincinnati',
  },
  {
    id: '228',
    name: 'Clemson',
    statName: 'Clemson',
    kpName: 'Clemson',
  },
  {
    id: '325',
    name: 'Cleveland State',
    statName: 'Cleveland State',
    kpName: 'Cleveland St.',
  },
  {
    id: '324',
    name: 'Coastal Carolina',
    statName: 'Coastal Carolina',
    kpName: 'Coastal Carolina',
  },
  {
    id: '2142',
    name: 'Colgate',
    statName: 'Colgate',
    kpName: 'Colgate',
  },
  {
    id: '38',
    name: 'Colorado',
    statName: 'Colorado',
    kpName: 'Colorado',
  },
  {
    id: '36',
    name: 'Colorado State',
    statName: 'Colorado State',
    kpName: 'Colorado St.',
  },
  {
    id: '171',
    name: 'Columbia',
    statName: 'Columbia',
    kpName: 'Columbia',
  },
  {
    id: '2154',
    name: 'Coppin State',
    statName: 'Coppin State',
    kpName: 'Coppin St.',
  },
  {
    id: '172',
    name: 'Cornell',
    statName: 'Cornell',
    kpName: 'Cornell',
  },
  {
    id: '156',
    name: 'Creighton',
    statName: 'Creighton',
    kpName: 'Creighton',
  },
  {
    id: '159',
    name: 'Dartmouth',
    statName: 'Dartmouth',
    kpName: 'Dartmouth',
  },
  {
    id: '2166',
    name: 'Davidson',
    statName: 'Davidson',
    kpName: 'Davidson',
  },
  {
    id: '2168',
    name: 'Dayton',
    statName: 'Dayton',
    kpName: 'Dayton',
  },
  {
    id: '305',
    name: 'DePaul',
    statName: 'DePaul',
    kpName: 'DePaul',
  },
  {
    id: '48',
    name: 'Delaware',
    statName: 'Delaware',
    kpName: 'Delaware',
  },
  {
    id: '2169',
    name: 'Delaware State',
    statName: 'Delaware State',
    kpName: 'Delaware St.',
  },
  {
    id: '2172',
    name: 'Denver',
    statName: 'Denver',
    kpName: 'Denver',
  },
  {
    id: '2174',
    name: 'Detroit Mercy',
    statName: 'Detroit Mercy',
    kpName: 'Detroit Mercy',
  },
  {
    id: '2181',
    name: 'Drake',
    statName: 'Drake',
    kpName: 'Drake',
  },
  {
    id: '2182',
    name: 'Drexel',
    statName: 'Drexel',
    kpName: 'Drexel',
  },
  {
    id: '150',
    name: 'Duke',
    statName: 'Duke',
    kpName: 'Duke',
  },
  {
    id: '2184',
    name: 'Duquesne',
    statName: 'Duquesne',
    kpName: 'Duquesne',
  },
  {
    id: '151',
    name: 'East Carolina',
    statName: 'East Carolina',
    kpName: 'East Carolina',
  },
  {
    id: '2193',
    name: 'East Tennessee State',
    statName: 'East Tennessee State',
    kpName: 'East Tennessee St.',
  },
  {
    id: '2197',
    name: 'Eastern Illinois',
    statName: 'Eastern Illinois',
    kpName: 'Eastern Illinois',
  },
  {
    id: '2198',
    name: 'Eastern Kentucky',
    statName: 'Eastern Kentucky',
    kpName: 'Eastern Kentucky',
  },
  {
    id: '2199',
    name: 'Eastern Michigan',
    statName: 'Eastern Michigan',
    kpName: 'Eastern Michigan',
  },
  {
    id: '331',
    name: 'Eastern Washington',
    statName: 'Eastern Washington',
    kpName: 'Eastern Washington',
  },
  {
    id: '2210',
    name: 'Elon',
    statName: 'Elon',
    kpName: 'Elon',
  },
  {
    id: '339',
    name: 'Evansville',
    statName: 'Evansville',
    kpName: 'Evansville',
  },
  {
    id: '2217',
    name: 'Fairfield',
    statName: 'Fairfield',
    kpName: 'Fairfield',
  },
  {
    id: '161',
    name: 'Fairleigh Dickinson',
    statName: 'Fairleigh Dickinson',
    kpName: 'Fairleigh Dickinson',
  },
  {
    id: '50',
    name: 'Florida A&M',
    statName: 'Florida A&M',
    kpName: 'Florida A&M',
  },
  {
    id: '2226',
    name: 'Florida Atlantic',
    statName: 'Florida Atlantic',
    kpName: 'Florida Atlantic',
  },
  {
    id: '57',
    name: 'Florida',
    statName: 'Florida',
    kpName: 'Florida',
  },
  {
    id: '526',
    name: 'Florida Gulf Coast',
    statName: 'Florida Gulf Coast',
    kpName: 'Florida Gulf Coast',
  },
  {
    id: '2229',
    name: 'Florida International',
    statName: 'Florida International',
    kpName: 'FIU',
  },
  {
    id: '52',
    name: 'Florida State',
    statName: 'Florida State',
    kpName: 'Florida St.',
  },
  {
    id: '2230',
    name: 'Fordham',
    statName: 'Fordham',
    kpName: 'Fordham',
  },
  {
    id: '278',
    name: 'Fresno State',
    statName: 'Fresno State',
    kpName: 'Fresno St.',
  },
  {
    id: '231',
    name: 'Furman',
    statName: 'Furman',
    kpName: 'Furman',
  },
  {
    id: '2241',
    name: 'Gardner-Webb',
    statName: 'Gardner-Webb',
    kpName: 'Gardner Webb',
  },
  {
    id: '2244',
    name: 'George Mason',
    statName: 'George Mason',
    kpName: 'George Mason',
  },
  {
    id: '45',
    name: 'George Washington',
    statName: 'George Washington',
    kpName: 'George Washington',
  },
  {
    id: '46',
    name: 'Georgetown',
    statName: 'Georgetown',
    kpName: 'Georgetown',
  },
  {
    id: '61',
    name: 'Georgia',
    statName: 'Georgia',
    kpName: 'Georgia',
  },
  {
    id: '290',
    name: 'Georgia Southern',
    statName: 'Georgia Southern',
    kpName: 'Georgia Southern',
  },
  {
    id: '2247',
    name: 'Georgia State',
    statName: 'Georgia State',
    kpName: 'Georgia St.',
  },
  {
    id: '59',
    name: 'Georgia Tech',
    statName: 'Georgia Tech',
    kpName: 'Georgia Tech',
  },
  {
    id: '2250',
    name: 'Gonzaga',
    statName: 'Gonzaga',
    kpName: 'Gonzaga',
  },
  {
    id: '2755',
    name: 'Grambling',
    statName: 'Grambling',
    kpName: 'Grambling St.',
  },
  {
    id: '2253',
    name: 'Grand Canyon',
    statName: 'Grand Canyon',
    kpName: 'Grand Canyon',
  },
  {
    id: '2739',
    name: 'Green Bay',
    statName: 'Green Bay',
    kpName: 'Green Bay',
  },
  {
    id: '2261',
    name: 'Hampton',
    statName: 'Hampton',
    kpName: 'Hampton',
  },
  {
    id: '42',
    name: 'Hartford',
    statName: 'Hartford',
    kpName: 'Hartford',
  },
  {
    id: '108',
    name: 'Harvard',
    statName: 'Harvard',
    kpName: 'Harvard',
  },
  {
    id: '62',
    name: "Hawai'i",
    statName: 'Hawaii',
    kpName: 'Hawaii',
  },
  {
    id: '2272',
    name: 'High Point',
    statName: 'High Point',
    kpName: 'High Point',
  },
  {
    id: '2275',
    name: 'Hofstra',
    statName: 'Hofstra',
    kpName: 'Hofstra',
  },
  {
    id: '107',
    name: 'Holy Cross',
    statName: 'Holy Cross',
    kpName: 'Holy Cross',
  },
  {
    id: '2277',
    name: 'Houston Baptist',
    statName: 'Houston Baptist',
    kpName: 'Houston Baptist',
  },
  {
    id: '248',
    name: 'Houston',
    statName: 'Houston',
    kpName: 'Houston',
  },
  {
    id: '47',
    name: 'Howard',
    statName: 'Howard',
    kpName: 'Howard',
  },
  {
    id: '85',
    name: 'IUPUI',
    statName: 'IUPUI',
    kpName: 'IUPUI',
  },
  {
    id: '304',
    name: 'Idaho State',
    statName: 'Idaho State',
    kpName: 'Idaho St.',
  },
  {
    id: '70',
    name: 'Idaho',
    statName: 'Idaho',
    kpName: 'Idaho',
  },
  {
    id: '356',
    name: 'Illinois',
    statName: 'Illinois',
    kpName: 'Illinois',
  },
  {
    id: '2287',
    name: 'Illinois State',
    statName: 'Illinois State',
    kpName: 'Illinois St.',
  },
  {
    id: '2916',
    name: 'Incarnate Word',
    statName: 'Incarnate Word',
    kpName: 'Incarnate Word',
  },
  {
    id: '84',
    name: 'Indiana',
    statName: 'Indiana',
    kpName: 'Indiana',
  },
  {
    id: '282',
    name: 'Indiana State',
    statName: 'Indiana State',
    kpName: 'Indiana St.',
  },
  {
    id: '314',
    name: 'Iona',
    statName: 'Iona',
    kpName: 'Iona',
  },
  {
    id: '2294',
    name: 'Iowa',
    statName: 'Iowa',
    kpName: 'Iowa',
  },
  {
    id: '66',
    name: 'Iowa State',
    statName: 'Iowa State',
    kpName: 'Iowa St.',
  },
  {
    id: '2296',
    name: 'Jackson State',
    statName: 'Jackson State',
    kpName: 'Jackson St.',
  },
  {
    id: '294',
    name: 'Jacksonville',
    statName: 'Jacksonville',
    kpName: 'Jacksonville',
  },
  {
    id: '55',
    name: 'Jacksonville State',
    statName: 'Jacksonville State',
    kpName: 'Jacksonville St.',
  },
  {
    id: '256',
    name: 'James Madison',
    statName: 'James Madison',
    kpName: 'James Madison',
  },
  {
    id: '2305',
    name: 'Kansas',
    statName: 'Kansas',
    kpName: 'Kansas',
  },
  {
    id: '2306',
    name: 'Kansas State',
    statName: 'Kansas State',
    kpName: 'Kansas St.',
  },
  {
    id: '338',
    name: 'Kennesaw State',
    statName: 'Kennesaw State',
    kpName: 'Kennesaw St.',
  },
  {
    id: '2309',
    name: 'Kent State',
    statName: 'Kent State',
    kpName: 'Kent St.',
  },
  {
    id: '96',
    name: 'Kentucky',
    statName: 'Kentucky',
    kpName: 'Kentucky',
  },
  {
    id: '99',
    name: 'LSU',
    statName: 'Louisiana State',
    kpName: 'LSU',
  },
  {
    id: '2325',
    name: 'La Salle',
    statName: 'La Salle',
    kpName: 'La Salle',
  },
  {
    id: '322',
    name: 'Lafayette',
    statName: 'Lafayette',
    kpName: 'Lafayette',
  },
  {
    id: '2320',
    name: 'Lamar',
    statName: 'Lamar',
    kpName: 'Lamar',
  },
  {
    id: '2329',
    name: 'Lehigh',
    statName: 'Lehigh',
    kpName: 'Lehigh',
  },
  {
    id: '2335',
    name: 'Liberty',
    statName: 'Liberty',
    kpName: 'Liberty',
  },
  {
    id: '288',
    name: 'Lipscomb',
    statName: 'Lipscomb',
    kpName: 'Lipscomb',
  },
  {
    id: '2031',
    name: 'Little Rock',
    statName: 'Little Rock',
    kpName: 'Little Rock',
  },
  {
    id: '299',
    name: 'Long Beach State',
    statName: 'Long Beach State',
    kpName: 'Long Beach St.',
  },
  {
    id: '112358',
    name: 'Long Island University',
    statName: 'Long Island University',
    kpName: 'LIU',
  },
  {
    id: '2344',
    name: 'Longwood',
    statName: 'Longwood',
    kpName: 'Longwood',
  },
  {
    id: '309',
    name: 'Louisiana',
    statName: 'Louisiana',
    kpName: 'Louisiana',
  },
  {
    id: '2348',
    name: 'Louisiana Tech',
    statName: 'Louisiana Tech',
    kpName: 'Louisiana Tech',
  },
  {
    id: '97',
    name: 'Louisville',
    statName: 'Louisville',
    kpName: 'Louisville',
  },
  {
    id: '2352',
    name: 'Loyola (MD)',
    statName: 'Loyola (MD)',
    kpName: 'Loyola MD',
  },
  {
    id: '2350',
    name: 'Loyola Chicago',
    statName: 'Loyola (IL)',
    kpName: 'Loyola Chicago',
  },
  {
    id: '2351',
    name: 'Loyola Marymount',
    statName: 'Loyola Marymount',
    kpName: 'Loyola Marymount',
  },
  {
    id: '311',
    name: 'Maine',
    statName: 'Maine',
    kpName: 'Maine',
  },
  {
    id: '2363',
    name: 'Manhattan',
    statName: 'Manhattan',
    kpName: 'Manhattan',
  },
  {
    id: '2368',
    name: 'Marist',
    statName: 'Marist',
    kpName: 'Marist',
  },
  {
    id: '269',
    name: 'Marquette',
    statName: 'Marquette',
    kpName: 'Marquette',
  },
  {
    id: '276',
    name: 'Marshall',
    statName: 'Marshall',
    kpName: 'Marshall',
  },
  {
    id: '120',
    name: 'Maryland',
    statName: 'Maryland',
    kpName: 'Maryland',
  },
  {
    id: '2379',
    name: 'Maryland-Eastern Shore',
    statName: 'Maryland-Eastern Shore',
    kpName: 'Maryland Eastern Shore',
  },
  {
    id: '2377',
    name: 'McNeese',
    statName: 'McNeese State',
    kpName: 'McNeese',
  },
  {
    id: '235',
    name: 'Memphis',
    statName: 'Memphis',
    kpName: 'Memphis',
  },
  {
    id: '2382',
    name: 'Mercer',
    statName: 'Mercer',
    kpName: 'Mercer',
  },
  {
    id: '2771',
    name: 'Merrimack',
    statName: 'Merrimack',
    kpName: 'Merrimack',
  },
  {
    id: '193',
    name: 'Miami (OH)',
    statName: 'Miami (OH)',
    kpName: 'Miami OH',
  },
  {
    id: '2390',
    name: 'Miami',
    statName: 'Miami (FL)',
    kpName: 'Miami FL',
  },
  {
    id: '127',
    name: 'Michigan State',
    statName: 'Michigan State',
    kpName: 'Michigan St.',
  },
  {
    id: '130',
    name: 'Michigan',
    statName: 'Michigan',
    kpName: 'Michigan',
  },
  {
    id: '2393',
    name: 'Middle Tennessee',
    statName: 'Middle Tennessee',
    kpName: 'Middle Tennessee',
  },
  {
    id: '270',
    name: 'Milwaukee',
    statName: 'Milwaukee',
    kpName: 'Milwaukee',
  },
  {
    id: '135',
    name: 'Minnesota',
    statName: 'Minnesota',
    kpName: 'Minnesota',
  },
  {
    id: '344',
    name: 'Mississippi State',
    statName: 'Mississippi State',
    kpName: 'Mississippi St.',
  },
  {
    id: '2400',
    name: 'Mississippi Valley State',
    statName: 'Mississippi Valley State',
    kpName: 'Mississippi Valley St.',
  },
  {
    id: '2623',
    name: 'Missouri State',
    statName: 'Missouri State',
    kpName: 'Missouri St.',
  },
  {
    id: '142',
    name: 'Missouri',
    statName: 'Missouri',
    kpName: 'Missouri',
  },
  {
    id: '2405',
    name: 'Monmouth',
    statName: 'Monmouth',
    kpName: 'Monmouth',
  },
  {
    id: '149',
    name: 'Montana',
    statName: 'Montana',
    kpName: 'Montana',
  },
  {
    id: '147',
    name: 'Montana State',
    statName: 'Montana State',
    kpName: 'Montana St.',
  },
  {
    id: '2413',
    name: 'Morehead State',
    statName: 'Morehead State',
    kpName: 'Morehead St.',
  },
  {
    id: '2415',
    name: 'Morgan State',
    statName: 'Morgan State',
    kpName: 'Morgan St.',
  },
  {
    id: '116',
    name: "Mt. St. Mary's",
    statName: "Mount St. Mary's",
    kpName: "Mount St. Mary's",
  },
  {
    id: '93',
    name: 'Murray State',
    statName: 'Murray State',
    kpName: 'Murray St.',
  },
  {
    id: '152',
    name: 'NC State',
    statName: 'North Carolina State',
    kpName: 'N.C. State',
  },
  {
    id: '2885',
    name: 'NJIT',
    statName: 'NJIT',
    kpName: 'NJIT',
  },
  {
    id: '2426',
    name: 'Navy',
    statName: 'Navy',
    kpName: 'Navy',
  },
  {
    id: '158',
    name: 'Nebraska',
    statName: 'Nebraska',
    kpName: 'Nebraska',
  },
  {
    id: '2440',
    name: 'Nevada',
    statName: 'Nevada',
    kpName: 'Nevada',
  },
  {
    id: '160',
    name: 'New Hampshire',
    statName: 'New Hampshire',
    kpName: 'New Hampshire',
  },
  {
    id: '167',
    name: 'New Mexico',
    statName: 'New Mexico',
    kpName: 'New Mexico',
  },
  {
    id: '166',
    name: 'New Mexico State',
    statName: 'New Mexico State',
    kpName: 'New Mexico St.',
  },
  {
    id: '2443',
    name: 'New Orleans',
    statName: 'New Orleans',
    kpName: 'New Orleans',
  },
  {
    id: '315',
    name: 'Niagara',
    statName: 'Niagara',
    kpName: 'Niagara',
  },
  {
    id: '2447',
    name: 'Nicholls',
    statName: 'Nicholls State',
    kpName: 'Nicholls St.',
  },
  {
    id: '2450',
    name: 'Norfolk State',
    statName: 'Norfolk State',
    kpName: 'Norfolk St.',
  },
  {
    id: '2453',
    name: 'North Alabama',
    statName: 'North Alabama',
    kpName: 'North Alabama',
  },
  {
    id: '2448',
    name: 'North Carolina A&T',
    statName: 'North Carolina A&T',
    kpName: 'North Carolina A&T',
  },
  {
    id: '2428',
    name: 'North Carolina Central',
    statName: 'North Carolina Central',
    kpName: 'North Carolina Central',
  },
  {
    id: '153',
    name: 'North Carolina',
    statName: 'North Carolina',
    kpName: 'North Carolina',
  },
  {
    id: '155',
    name: 'North Dakota',
    statName: 'North Dakota',
    kpName: 'North Dakota',
  },
  {
    id: '2449',
    name: 'North Dakota State',
    statName: 'North Dakota State',
    kpName: 'North Dakota St.',
  },
  {
    id: '2454',
    name: 'North Florida',
    statName: 'North Florida',
    kpName: 'North Florida',
  },
  {
    id: '249',
    name: 'North Texas',
    statName: 'North Texas',
    kpName: 'North Texas',
  },
  {
    id: '111',
    name: 'Northeastern',
    statName: 'Northeastern',
    kpName: 'Northeastern',
  },
  {
    id: '2464',
    name: 'Northern Arizona',
    statName: 'Northern Arizona',
    kpName: 'Northern Arizona',
  },
  {
    id: '2458',
    name: 'Northern Colorado',
    statName: 'Northern Colorado',
    kpName: 'Northern Colorado',
  },
  {
    id: '2459',
    name: 'Northern Illinois',
    statName: 'Northern Illinois',
    kpName: 'Northern Illinois',
  },
  {
    id: '2460',
    name: 'Northern Iowa',
    statName: 'Northern Iowa',
    kpName: 'Northern Iowa',
  },
  {
    id: '94',
    name: 'Northern Kentucky',
    statName: 'Northern Kentucky',
    kpName: 'Northern Kentucky',
  },
  {
    id: '2466',
    name: 'Northwestern State',
    statName: 'Northwestern State',
    kpName: 'Northwestern St.',
  },
  {
    id: '77',
    name: 'Northwestern',
    statName: 'Northwestern',
    kpName: 'Northwestern',
  },
  {
    id: '87',
    name: 'Notre Dame',
    statName: 'Notre Dame',
    kpName: 'Notre Dame',
  },
  {
    id: '2473',
    name: 'Oakland',
    statName: 'Oakland',
    kpName: 'Oakland',
  },
  {
    id: '195',
    name: 'Ohio',
    statName: 'Ohio',
    kpName: 'Ohio',
  },
  {
    id: '194',
    name: 'Ohio State',
    statName: 'Ohio State',
    kpName: 'Ohio St.',
  },
  {
    id: '201',
    name: 'Oklahoma',
    statName: 'Oklahoma',
    kpName: 'Oklahoma',
  },
  {
    id: '197',
    name: 'Oklahoma State',
    statName: 'Oklahoma State',
    kpName: 'Oklahoma St.',
  },
  {
    id: '295',
    name: 'Old Dominion',
    statName: 'Old Dominion',
    kpName: 'Old Dominion',
  },
  {
    id: '145',
    name: 'Ole Miss',
    statName: 'Mississippi',
    kpName: 'Mississippi',
  },
  {
    id: '2437',
    name: 'Omaha',
    statName: 'Omaha',
    kpName: 'Nebraska Omaha',
  },
  {
    id: '198',
    name: 'Oral Roberts',
    statName: 'Oral Roberts',
    kpName: 'Oral Roberts',
  },
  {
    id: '2483',
    name: 'Oregon',
    statName: 'Oregon',
    kpName: 'Oregon',
  },
  {
    id: '204',
    name: 'Oregon State',
    statName: 'Oregon State',
    kpName: 'Oregon St.',
  },
  {
    id: '279',
    name: 'Pacific',
    statName: 'Pacific',
    kpName: 'Pacific',
  },
  {
    id: '213',
    name: 'Penn State',
    statName: 'Penn State',
    kpName: 'Penn St.',
  },
  {
    id: '219',
    name: 'Pennsylvania',
    statName: 'Pennsylvania',
    kpName: 'Penn',
  },
  {
    id: '2492',
    name: 'Pepperdine',
    statName: 'Pepperdine',
    kpName: 'Pepperdine',
  },
  {
    id: '221',
    name: 'Pittsburgh',
    statName: 'Pittsburgh',
    kpName: 'Pittsburgh',
  },
  {
    id: '2501',
    name: 'Portland',
    statName: 'Portland',
    kpName: 'Portland',
  },
  {
    id: '2502',
    name: 'Portland State',
    statName: 'Portland State',
    kpName: 'Portland St.',
  },
  {
    id: '2504',
    name: 'Prairie View A&M',
    statName: 'Prairie View',
    kpName: 'Prairie View A&M',
  },
  {
    id: '2506',
    name: 'Presbyterian',
    statName: 'Presbyterian',
    kpName: 'Presbyterian',
  },
  {
    id: '163',
    name: 'Princeton',
    statName: 'Princeton',
    kpName: 'Princeton',
  },
  {
    id: '2507',
    name: 'Providence',
    statName: 'Providence',
    kpName: 'Providence',
  },
  {
    id: '2509',
    name: 'Purdue',
    statName: 'Purdue',
    kpName: 'Purdue',
  },
  {
    id: '2870',
    name: 'Purdue Fort Wayne',
    statName: 'Purdue-Fort Wayne',
    kpName: 'Purdue Fort Wayne',
  },
  {
    id: '2514',
    name: 'Quinnipiac',
    statName: 'Quinnipiac',
    kpName: 'Quinnipiac',
  },
  {
    id: '2515',
    name: 'Radford',
    statName: 'Radford',
    kpName: 'Radford',
  },
  {
    id: '227',
    name: 'Rhode Island',
    statName: 'Rhode Island',
    kpName: 'Rhode Island',
  },
  {
    id: '242',
    name: 'Rice',
    statName: 'Rice',
    kpName: 'Rice',
  },
  {
    id: '257',
    name: 'Richmond',
    statName: 'Richmond',
    kpName: 'Richmond',
  },
  {
    id: '2520',
    name: 'Rider',
    statName: 'Rider',
    kpName: 'Rider',
  },
  {
    id: '2523',
    name: 'Robert Morris',
    statName: 'Robert Morris',
    kpName: 'Robert Morris',
  },
  {
    id: '164',
    name: 'Rutgers',
    statName: 'Rutgers',
    kpName: 'Rutgers',
  },
  {
    id: '2545',
    name: 'SE Louisiana',
    statName: 'Southeastern Louisiana',
    kpName: 'Southeastern Louisiana',
  },
  {
    id: '2546',
    name: 'SE Missouri St',
    statName: 'Southeast Missouri State',
    kpName: 'Southeast Missouri St.',
  },
  {
    id: '2565',
    name: 'SIU-Edwardsville',
    statName: 'SIU Edwardsville',
    kpName: 'SIUE',
  },
  {
    id: '2567',
    name: 'SMU',
    statName: 'Southern Methodist',
    kpName: 'SMU',
  },
  {
    id: '16',
    name: 'Sacramento State',
    statName: 'Sacramento State',
    kpName: 'Sacramento St.',
  },
  {
    id: '2529',
    name: 'Sacred Heart',
    statName: 'Sacred Heart',
    kpName: 'Sacred Heart',
  },
  {
    id: '2603',
    name: "Saint Joseph's",
    statName: "Saint Joseph's",
    kpName: "Saint Joseph's",
  },
  {
    id: '139',
    name: 'Saint Louis',
    statName: 'Saint Louis',
    kpName: 'Saint Louis',
  },
  {
    id: '2608',
    name: "Saint Mary's",
    statName: "Saint Mary's (CA)",
    kpName: "Saint Mary's",
  },
  {
    id: '2612',
    name: "Saint Peter's",
    statName: "Saint Peter's",
    kpName: "Saint Peter's",
  },
  {
    id: '2534',
    name: 'Sam Houston State',
    statName: 'Sam Houston State',
    kpName: 'Sam Houston St.',
  },
  {
    id: '2535',
    name: 'Samford',
    statName: 'Samford',
    kpName: 'Samford',
  },
  {
    id: '21',
    name: 'San Diego State',
    statName: 'San Diego State',
    kpName: 'San Diego St.',
  },
  {
    id: '301',
    name: 'San Diego',
    statName: 'San Diego',
    kpName: 'San Diego',
  },
  {
    id: '2539',
    name: 'San Francisco',
    statName: 'San Francisco',
    kpName: 'San Francisco',
  },
  {
    id: '23',
    name: 'San José St',
    statName: 'San Jose State',
    kpName: 'San Jose St.',
  },
  {
    id: '2541',
    name: 'Santa Clara',
    statName: 'Santa Clara',
    kpName: 'Santa Clara',
  },
  {
    id: '2547',
    name: 'Seattle',
    statName: 'Seattle',
    kpName: 'Seattle',
  },
  {
    id: '2550',
    name: 'Seton Hall',
    statName: 'Seton Hall',
    kpName: 'Seton Hall',
  },
  {
    id: '2561',
    name: 'Siena',
    statName: 'Siena',
    kpName: 'Siena',
  },
  {
    id: '6',
    name: 'South Alabama',
    statName: 'South Alabama',
    kpName: 'South Alabama',
  },
  {
    id: '2579',
    name: 'South Carolina',
    statName: 'South Carolina',
    kpName: 'South Carolina',
  },
  {
    id: '2569',
    name: 'South Carolina State',
    statName: 'South Carolina State',
    kpName: 'South Carolina St.',
  },
  {
    id: '2908',
    name: 'South Carolina Upstate',
    statName: 'South Carolina Upstate',
    kpName: 'USC Upstate',
  },
  {
    id: '233',
    name: 'South Dakota',
    statName: 'South Dakota',
    kpName: 'South Dakota',
  },
  {
    id: '2571',
    name: 'South Dakota State',
    statName: 'South Dakota State',
    kpName: 'South Dakota St.',
  },
  {
    id: '58',
    name: 'South Florida',
    statName: 'South Florida',
    kpName: 'South Florida',
  },
  {
    id: '79',
    name: 'Southern Illinois',
    statName: 'Southern Illinois',
    kpName: 'Southern Illinois',
  },
  {
    id: '2582',
    name: 'Southern',
    statName: 'Southern',
    kpName: 'Southern',
  },
  {
    id: '2572',
    name: 'Southern Miss',
    statName: 'Southern Mississippi',
    kpName: 'Southern Miss',
  },
  {
    id: '253',
    name: 'Southern Utah',
    statName: 'Southern Utah',
    kpName: 'Southern Utah',
  },
  {
    id: '179',
    name: 'St. Bonaventure',
    statName: 'St. Bonaventure',
    kpName: 'St. Bonaventure',
  },
  {
    id: '2597',
    name: 'St. Francis (BKN)',
    statName: 'St. Francis (NY)',
    kpName: 'St. Francis NY',
  },
  {
    id: '2598',
    name: 'St. Francis (PA)',
    statName: 'Saint Francis (PA)',
    kpName: 'St. Francis PA',
  },
  {
    id: '2599',
    name: "St. John's",
    statName: "St. John's (NY)",
    kpName: "St. John's",
  },
  {
    id: '24',
    name: 'Stanford',
    statName: 'Stanford',
    kpName: 'Stanford',
  },
  {
    id: '2617',
    name: 'Stephen F. Austin',
    statName: 'Stephen F. Austin',
    kpName: 'Stephen F. Austin',
  },
  {
    id: '56',
    name: 'Stetson',
    statName: 'Stetson',
    kpName: 'Stetson',
  },
  {
    id: '2619',
    name: 'Stony Brook',
    statName: 'Stony Brook',
    kpName: 'Stony Brook',
  },
  {
    id: '183',
    name: 'Syracuse',
    statName: 'Syracuse',
    kpName: 'Syracuse',
  },
  {
    id: '2628',
    name: 'TCU',
    statName: 'TCU',
    kpName: 'TCU',
  },
  {
    id: '218',
    name: 'Temple',
    statName: 'Temple',
    kpName: 'Temple',
  },
  {
    id: '2634',
    name: 'Tennessee State',
    statName: 'Tennessee State',
    kpName: 'Tennessee St.',
  },
  {
    id: '2635',
    name: 'Tennessee Tech',
    statName: 'Tennessee Tech',
    kpName: 'Tennessee Tech',
  },
  {
    id: '2633',
    name: 'Tennessee',
    statName: 'Tennessee',
    kpName: 'Tennessee',
  },
  {
    id: '245',
    name: 'Texas A&M',
    statName: 'Texas A&M',
    kpName: 'Texas A&M',
  },
  {
    id: '357',
    name: 'Texas A&M-CC',
    statName: 'Texas A&M-Corpus Christi',
    kpName: 'Texas A&M Corpus Chris',
  },
  {
    id: '251',
    name: 'Texas',
    statName: 'Texas',
    kpName: 'Texas',
  },
  {
    id: '2640',
    name: 'Texas Southern',
    statName: 'Texas Southern',
    kpName: 'Texas Southern',
  },
  {
    id: '326',
    name: 'Texas State',
    statName: 'Texas State',
    kpName: 'Texas St.',
  },
  {
    id: '2641',
    name: 'Texas Tech',
    statName: 'Texas Tech',
    kpName: 'Texas Tech',
  },
  {
    id: '2643',
    name: 'The Citadel',
    statName: 'Citadel',
    kpName: 'The Citadel',
  },
  {
    id: '2649',
    name: 'Toledo',
    statName: 'Toledo',
    kpName: 'Toledo',
  },
  {
    id: '119',
    name: 'Towson',
    statName: 'Towson',
    kpName: 'Towson',
  },
  {
    id: '2653',
    name: 'Troy',
    statName: 'Troy',
    kpName: 'Troy',
  },
  {
    id: '2655',
    name: 'Tulane',
    statName: 'Tulane',
    kpName: 'Tulane',
  },
  {
    id: '202',
    name: 'Tulsa',
    statName: 'Tulsa',
    kpName: 'Tulsa',
  },
  {
    id: '5',
    name: 'UAB',
    statName: 'UAB',
    kpName: 'UAB',
  },
  {
    id: '302',
    name: 'UC Davis',
    statName: 'UC-Davis',
    kpName: 'UC Davis',
  },
  {
    id: '300',
    name: 'UC Irvine',
    statName: 'UC-Irvine',
    kpName: 'UC Irvine',
  },
  {
    id: '27',
    name: 'UC Riverside',
    statName: 'UC-Riverside',
    kpName: 'UC Riverside',
  },
  {
    id: '2540',
    name: 'UC Santa Barbara',
    statName: 'UC-Santa Barbara',
    kpName: 'UC Santa Barbara',
  },
  {
    id: '2116',
    name: 'UCF',
    statName: 'Central Florida',
    kpName: 'UCF',
  },
  {
    id: '26',
    name: 'UCLA',
    statName: 'UCLA',
    kpName: 'UCLA',
  },
  {
    id: '41',
    name: 'UConn',
    statName: 'Connecticut',
    kpName: 'Connecticut',
  },
  {
    id: '82',
    name: 'UIC',
    statName: 'Illinois-Chicago',
    kpName: 'Illinois Chicago',
  },
  {
    id: '2433',
    name: 'UL Monroe',
    statName: 'Louisiana-Monroe',
    kpName: 'Louisiana Monroe',
  },
  {
    id: '2378',
    name: 'UMBC',
    statName: 'Maryland-Baltimore County',
    kpName: 'UMBC',
  },
  {
    id: '140',
    name: 'UMKC',
    statName: 'Missouri-Kansas City',
    kpName: 'UMKC',
  },
  {
    id: '2349',
    name: 'UMass Lowell',
    statName: 'Massachusetts-Lowell',
    kpName: 'UMass Lowell',
  },
  {
    id: '113',
    name: 'UMass',
    statName: 'Massachusetts-Lowell',
    kpName: 'Massachusetts',
  },
  {
    id: '2427',
    name: 'UNC Asheville',
    statName: 'North Carolina-Asheville',
    kpName: 'UNC Asheville',
  },
  {
    id: '2430',
    name: 'UNC Greensboro',
    statName: 'North Carolina-Greensboro',
    kpName: 'UNC Greensboro',
  },
  {
    id: '350',
    name: 'UNC Wilmington',
    statName: 'UNC Wilmington',
    kpName: 'UNC Wilmington',
  },
  {
    id: '2439',
    name: 'UNLV',
    statName: 'Nevada-Las Vegas',
    kpName: 'UNLV',
  },
  {
    id: '30',
    name: 'USC',
    statName: 'Southern California',
    kpName: 'USC',
  },
  {
    id: '250',
    name: 'UT Arlington',
    statName: 'Texas-Arlington',
    kpName: 'UT Arlington',
  },
  {
    id: '2630',
    name: 'UT Martin',
    statName: 'Tennessee-Martin',
    kpName: 'Tennessee Martin',
  },
  {
    id: '292',
    name: 'UT Rio Grande Valley',
    statName: 'Texas-Rio Grande Valley',
    kpName: 'UT Rio Grande Valley',
  },
  {
    id: '2638',
    name: 'UTEP',
    statName: 'Texas-El Paso',
    kpName: 'UTEP',
  },
  {
    id: '2636',
    name: 'UTSA',
    statName: 'Texas-San Antonio',
    kpName: 'UTSA',
  },
  {
    id: '328',
    name: 'Utah State',
    statName: 'Utah State',
    kpName: 'Utah St.',
  },
  {
    id: '254',
    name: 'Utah',
    statName: 'Utah',
    kpName: 'Utah',
  },
  {
    id: '3084',
    name: 'Utah Valley',
    statName: 'Utah Valley',
    kpName: 'Utah Valley',
  },
  {
    id: '2670',
    name: 'VCU',
    statName: 'Virginia Commonwealth',
    kpName: 'VCU',
  },
  {
    id: '2678',
    name: 'VMI',
    statName: 'VMI',
    kpName: 'VMI',
  },
  {
    id: '2674',
    name: 'Valparaiso',
    statName: 'Valparaiso',
    kpName: 'Valparaiso',
  },
  {
    id: '238',
    name: 'Vanderbilt',
    statName: 'Vanderbilt',
    kpName: 'Vanderbilt',
  },
  {
    id: '261',
    name: 'Vermont',
    statName: 'Vermont',
    kpName: 'Vermont',
  },
  {
    id: '222',
    name: 'Villanova',
    statName: 'Villanova',
    kpName: 'Villanova',
  },
  {
    id: '258',
    name: 'Virginia',
    statName: 'Virginia',
    kpName: 'Virginia',
  },
  {
    id: '259',
    name: 'Virginia Tech',
    statName: 'Virginia Tech',
    kpName: 'Virginia Tech',
  },
  {
    id: '2681',
    name: 'Wagner',
    statName: 'Wagner',
    kpName: 'Wagner',
  },
  {
    id: '154',
    name: 'Wake Forest',
    statName: 'Wake Forest',
    kpName: 'Wake Forest',
  },
  {
    id: '264',
    name: 'Washington',
    statName: 'Washington',
    kpName: 'Washington',
  },
  {
    id: '265',
    name: 'Washington State',
    statName: 'Washington State',
    kpName: 'Washington St.',
  },
  {
    id: '2692',
    name: 'Weber State',
    statName: 'Weber State',
    kpName: 'Weber St.',
  },
  {
    id: '277',
    name: 'West Virginia',
    statName: 'West Virginia',
    kpName: 'West Virginia',
  },
  {
    id: '2717',
    name: 'Western Carolina',
    statName: 'Western Carolina',
    kpName: 'Western Carolina',
  },
  {
    id: '2710',
    name: 'Western Illinois',
    statName: 'Western Illinois',
    kpName: 'Western Illinois',
  },
  {
    id: '98',
    name: 'Western Kentucky',
    statName: 'Western Kentucky',
    kpName: 'Western Kentucky',
  },
  {
    id: '2711',
    name: 'Western Michigan',
    statName: 'Western Michigan',
    kpName: 'Western Michigan',
  },
  {
    id: '2724',
    name: 'Wichita State',
    statName: 'Wichita State',
    kpName: 'Wichita St.',
  },
  {
    id: '2729',
    name: 'William & Mary',
    statName: 'William & Mary',
    kpName: 'William & Mary',
  },
  {
    id: '2737',
    name: 'Winthrop',
    statName: 'Winthrop',
    kpName: 'Winthrop',
  },
  {
    id: '275',
    name: 'Wisconsin',
    statName: 'Wisconsin',
    kpName: 'Wisconsin',
  },
  {
    id: '2747',
    name: 'Wofford',
    statName: 'Wofford',
    kpName: 'Wofford',
  },
  {
    id: '2750',
    name: 'Wright State',
    statName: 'Wright State',
    kpName: 'Wright St.',
  },
  {
    id: '2751',
    name: 'Wyoming',
    statName: 'Wyoming',
    kpName: 'Wyoming',
  },
  {
    id: '2752',
    name: 'Xavier',
    statName: 'Xavier',
    kpName: 'Xavier',
  },
  {
    id: '43',
    name: 'Yale',
    statName: 'Yale',
    kpName: 'Yale',
  },
  {
    id: '2754',
    name: 'Youngstown St',
    statName: 'Youngstown State',
    kpName: 'Youngstown St.',
  },
  {
    id: '2837',
    name: 'Texas A&M-Commerce',
    statName: 'Texas A&M-Commerce',
    kpName: 'Texas A&M Commerce',
  },
  {
    id: '28',
    name: 'UC San Diego',
    statName: 'UC-San Diego',
    kpName: 'UC San Diego',
  }
];

export default teams;
